#!/usr/local/bin/python3
import json
import argparse
from pprint import pprint


parser = argparse.ArgumentParser()
parser.add_argument('path', type=str, help='the path to the .jsonl file')
args = parser.parse_args()


with open(args.path, 'r') as f:
    for line in f.readlines():
        pprint(json.loads(line))
